### ISSUE TITLE
Scale PVC for multi-tier component is broken

### ISSUE THREAD

**Issue by netixx** [datainfrahq/druid-operator#106]
I noticed on my cluster that the operator is trying to resize PVCs (and failing).

We have 2 tier of historicals, called histolder and histrecent, 
However, they are the right size, but it seems it's mixing the storage specs for the PVC : it's trying to resize the histolder PVC to the histrecent size...

It seems the `pvcLabels` here are too loose for matching the PVCs:
```
pvcLabels := map[string]string{
		"component": nodeSpec.NodeType,
	}

	pvcList, err := readers.List(ctx, sdk, drd, pvcLabels, emitEvent, func() objectList { return &v1.PersistentVolumeClaimList{} }, func(listObj runtime.Object) []object {
		items := listObj.(*v1.PersistentVolumeClaimList).Items
		result := make([]object, len(items))
		for i := 0; i < len(items); i++ {
			result[i] = &items[i]
		}
		return result
	})
	if err != nil {
		return nil
	}
```

It matches all historical nodes, regardless of the node name.

Here is a excerpt of my config:
```
  scalePvcSts: true
  nodes:
    histrecent:
      nodeType: "historical"
      #...
      volumeClaimTemplates:
        - metadata:
            name: data
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 400Gi
            storageClassName: csi-cinder-high-speed
      volumeMounts:
        - mountPath: /druid/data
          name: data
      volumes:
        - name: data
          emptyDir: {}

    histolder:
      nodeType: "historical"
      #...
      volumeClaimTemplates:
        - metadata:
            name: data
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 1200Gi
            storageClassName: csi-cinder-classic
      volumeMounts:
        - mountPath: /druid/data
          name: data
      volumes:
        - name: data
          emptyDir: {}

```

And here is the bit of operator log that caught my eye:
```
2023-09-11T15:04:22Z    ERROR   Reconciler error        {"controller": "druid", "controllerGroup": "druid.apache.org", "controllerKind": "Druid", "Druid": {"name":"x-cluster","namespace":"default"}, "namespace": "default", "name": "x-cluster", "reconcileID": "f8be13e6-fd34-428a-8f14-e3916e2e3112", "error": "PersistentVolumeClaim \"data-druid-x-cluster-histrecent-0\" is invalid: spec: Forbidden: spec is immutable after creation except resources.requests for bound claims\n  core.PersistentVolumeClaimSpec{\n  \tAccessModes: {\"ReadWriteOnce\"},\n  \tSelector:    nil,\n  \tResources: core.ResourceRequirements{\n  \t\tLimits:   nil,\n- \t\tRequests: core.ResourceList{s\"storage\": {i: resource.int64Amount{value: 429496729600}, Format: \"BinarySI\"}},\n+ \t\tRequests: core.ResourceList{s\"storage\": {i: resource.int64Amount{value: 1288490188800}, Format: \"BinarySI\"}},\n  \t},\n  \tVolumeName:       \"\",\n  \tStorageClassName: &\"csi-cinder-high-speed\",\n  \t... // 3 identical fields\n  }\n"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:329
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:274
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:235
2023-09-11T15:04:22Z    DEBUG   events  Error patching object [data-druid-x-cluster-histrecent-0:*v1.PersistentVolumeClaim] in namespace [default] due to [PersistentVolumeClaim "data-druid-x-cluster-histrecent-0" is invalid: spec: Forbidden: spec is immutable after creation except resources.requests for bound claims
  core.PersistentVolumeClaimSpec{
        AccessModes: {"ReadWriteOnce"},
        Selector:    nil,
        Resources: core.ResourceRequirements{
                Limits:   nil,
-               Requests: core.ResourceList{s"storage": {i: resource.int64Amount{value: 429496729600}, Format: "BinarySI"}},
+               Requests: core.ResourceList{s"storage": {i: resource.int64Amount{value: 1288490188800}, Format: "BinarySI"}},
        },
        VolumeName:       "",
        StorageClassName: &"csi-cinder-high-speed",
        ... // 3 identical fields
  }
```

Here are 2 successive (few minute interval) output from `k get pvc`:
```
data-druid-x-cluster-histolder-8          Bound    xxx     RWO            csi-cinder-classic      2m7s
data-druid-x-cluster-histolder-9          Bound    xxx   1200Gi     RWO            csi-cinder-classic      2m6s
data-druid-x-cluster-histrecent-0         Bound    xxx   400Gi      RWO            csi-cinder-high-speed   2m8s
data-druid-x-cluster-histrecent-1         Bound    xxx   400Gi      RWO            csi-cinder-high-speed   2m8s
```

```
data-druid-x-cluster-histolder-8          Bound    xxx   1200Gi     RWO            csi-cinder-classic      25m
data-druid-x-cluster-histolder-9          Bound    xxx   1200Gi     RWO            csi-cinder-classic      25m
data-druid-x-cluster-histrecent-0         Bound    xxx   1200Gi     RWO            csi-cinder-high-speed   25m
data-druid-x-cluster-histrecent-1         Bound    xxx   1200Gi     RWO            csi-cinder-high-speed   25m
```

As you can see, it ended up scaling all PVCs to 1200Gi because it keeps mixing up between the two values.
