### ISSUE TITLE
Support node-specific startupProbes 

### ISSUE THREAD

**Issue by schmichri** [datainfrahq/druid-operator#108]
Since operator 1.12.0 the setup of nodespecific nodes doesn't work any more. In my example the config of a coordinator looks the following:

```
nodes:
    coordinator:
      nodeType: "coordinator"
      druid.port: 8281
      nodeConfigMountPath: "/opt/druid/conf/druid/cluster/master/coordinator-overlord"
      replicas: 2
      podManagementPolicy: OrderedReady
      updateStrategy:
        type: RollingUpdate
      livenessProbe:
        failureThreshold: 60
        periodSeconds: 10
        httpGet:
          path: /status/health
          port: 8281
          scheme: HTTPS
      readinessProbe:
        failureThreshold: 60
        periodSeconds: 10
        httpGet:
          path: /status/health
          port: 8281
          scheme: HTTPS
      runtime.properties: |
        druid.service=druid/coordinator
        .... 
```

As you can see the cluster has TLS enabled and due to that I've used the default TLS Ports so for coordinator it's 8281, for router 9088, historical 8283, etc. 

With operator <=1.1.1 this works fine. Since Operator 1.2.0 the default_probes https://github.com/datainfrahq/druid-operator/pull/98  came in place and the node-specific probes config stopped working. 

Switching off the Defaultprobes with `spec.defaultProbes: false` a default startupProbe with will be set on the coordinator pod (via statefulset of course):

```
      livenessProbe:
        httpGet:
          path: /status/health
          port: 8281
          scheme: HTTPS
        timeoutSeconds: 1
        periodSeconds: 10
        successThreshold: 1
        failureThreshold: 60
      readinessProbe:
        httpGet:
          path: /status/health
          port: 8281
          scheme: HTTPS
        timeoutSeconds: 1
        periodSeconds: 10
        successThreshold: 1
        failureThreshold: 60
      startupProbe:
        httpGet:
          path: /status/health
          port: 8281
          scheme: HTTP
        initialDelaySeconds: 5
        timeoutSeconds: 5
        periodSeconds: 10
        successThreshold: 1
        failureThreshold: 10

```

The latest CRD doesn't allow to set node-specific startupProbes:

```
failed to create typed patch object (druid/fqmdruid; druid.apache.org/v1alpha1, Kind=Druid): .spec.nodes.coordinator.startupProbe: field not declared in schema
```

The changerequest would be, to allow the setup of node-specific startupProbes in the CRD.
