### ISSUE TITLE
Deleting the CR terminates unrelated PVs!

### ISSUE THREAD

**Issue by christian-schlichtherle** [datainfrahq/druid-operator#114]
I'm currently developing a Druid CR for production use. While testing the CR in our development environment, I'm repeatedly deleting and recreating the Druid CR. Unfortunately, it seems like whenever I delete the Druid CR, it not only deletes the orphaned PVCs which I have created using `persistentVolumeClaim` in the Druid spec, but somehow it terminates a completely unrelated persistent volume, even in other namespaces! We're using AWS EBS if that matters. I'm only lucky that these volumes are set to use the reclaim policy `Retain` or otherwise this would have already resulted in data loss! I was able to recover the volumes following the procedure described here: https://stackoverflow.com/a/59603862/733456

I suspect this is a bug as a side effect of deleting the orphaned PVCs, so I wonder how I can switch it off? The documentation is a bit confusing to me. I was also considering this blog post, but it didn't help much: https://www.rilldata.com/blog/setting-up-apache-druid-on-kubernetes-part-one

**Comment by AdheipSingh** [comment]
- Druid Operator will only delete orphan pvc which it owns.
- Druid Operator will delete a pvc after you delete the CR. If you [enabled](https://github.com/datainfrahq/druid-operator/blob/master/controllers/druid/handler.go#L94) this.
- Druid Operator will not delete any PVC it does not own. If you are using some other pvc in the same namespace which does not have any labels conflicting operator wont delete.

**Comment by christian-schlichtherle** [comment]
In order to avert further disaster, I have changed the CR spec as follows:

```yaml
spec:
  deleteOrphanPvc: false
  disablePVCDeletionFinalizer: true
```

I strongly recommend that these values should be default setting in the Druid CR! Why? Because that is the default behavior of a StatefulSet and it has been designed this way on purpose: When a StatefulSet gets deleted, it's PVCs remain untouched so that no data loss occurs, even if the reclaim policy of the associated PV is `delete`. This design choice is absolutely paramount:  IMHO, the Druid operator should not mess with PVCs unless explicitly asked to do so.

Now back to the original topic: Maybe there is a bug somehow or I did a misconfiguration. Here's the relevant part of my Druid CR:

```yaml
spec:
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 16Gi
        storageClassName: aws-ebs-retain  
```

As can be seen, I do not specify labels at `spec.volumeClaimTemplates[0].metadata.labels`. Should I?

Apparently, the PVCs created from this spec get labelled as follows:

```yaml
metadata:
  labels:
    component: broker
    druid_cr: foo-druid
    nodeSpecUniqueStr: druid-foo-druid-brokers
    [...]
```

This looks fine to me, but maybe there is a bug in the label matching algorithm?
