### ISSUE TITLE
druid-operator is crashed (segmentation fault) during creating PVC.

### ISSUE THREAD

**Issue by sunguck** [datainfrahq/druid-operator#118]
I am using druid-operator version 1.2.1.
During creating druid cluster, druid-operator pod is crashed with following panic message.
I have following pvc configuration for druid cluster.
```
apiVersion: "druid.apache.org/v1alpha1"
kind: "Druid"
metadata:
  name: abc-druid
spec:
  image: apache/druid:25.0.0
  ...
  scalePvcSts: true
  volumes:
    - name: volume-data-historical
      emptyDir: {}
  volumeMounts:
    - name: volume-data-historical
      mountPath: "/druid/historical"
    ...
    historicals:
      nodeType: "historical"
      druid.port: 8088
      nodeConfigMountPath: "/opt/druid/conf/druid/cluster/data/historical"
      replicas: 1
      ...
      volumeClaimTemplates:
        - metadata:
            name: volume-data-historical
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 100Gi
```

Stack trace of druid-operator.
```
2023-12-08T06:42:48Z INFO Observed a panic in reconciler: runtime error: invalid memory address or nil pointer dereference {"controller": "druid", "controllerGroup": "druid.apache.org", "controllerKind": "Druid", "Druid": {"name":"abc-druid","namespace":"abc-druid"}, "namespace": "abc-druid", "name": "abc-druid", "reconcileID": "0d7fdde5-a8b0-46eb-b8bc-678cd2ee1202"}
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
 panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x14c038e]
goroutine 460 [running]:
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
 /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:119 +0x1fa
panic({0x1646000, 0x2594d30})
 /usr/local/go/src/runtime/panic.go:884 +0x213
github.com/datainfrahq/druid-operator/controllers/druid.isVolumeExpansionEnabled({0x1a657c0, 0xc0009988a0}, {0x1a6c278, 0xc00069d140}, 0x1730560?, 0x1a6c278?, {0x1a6a6e0, 0xc000820480})
 /workspace/controllers/druid/handler.go:947 +0x12e
github.com/datainfrahq/druid-operator/controllers/druid.deployDruidCluster({0x1a657c0, 0xc0009988a0}, {0x1a6c278, 0xc00069d140}, 0xc00075c000, {0x1a6a6e0, 0xc000820480})
 /workspace/controllers/druid/handler.go:192 +0x12ff
github.com/datainfrahq/druid-operator/controllers/druid.(*DruidReconciler).Reconcile(0xc0007098b0, {0x1a657c0, 0xc0009988a0}, {{{0xc00081c6b0, 0x9}, {0xc00081c6a6, 0x9}}})
 /workspace/controllers/druid/druid_controller.go:75 +0x21b
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0x1a657c0?, {0x1a657c0?, 0xc0009988a0?}, {{{0xc00081c6b0?, 0x15ceaa0?}, {0xc00081c6a6?, 0x40f926?}}})
 /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:122 +0xc8
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc00019d360, {0x1a65718, 0xc000709810}, {0x169a0e0?, 0xc0007c21c0?})
 /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:323 +0x377
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc00019d360, {0x1a65718, 0xc000709810})
 /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:274 +0x1d9
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
 /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:235 +0x85
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
 /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:231 +0x587
```
