### ISSUE TITLE
Node Spec `podLabels` don't work if cluster spec `podLabels` are not defined

### ISSUE THREAD

**Issue by owais** [datainfrahq/druid-operator#183]
The following spec will not add any labels to pods (bug)

```yaml
apiVersion: "druid.apache.org/v1alpha1"
kind: "Druid"
metadata:
  name: tiny-cluster
spec:
  nodes:
    brokers:
      podLabels:
        label_a: yes
```

But the following will add both label_a and label_b (as expected)

```yaml
apiVersion: "druid.apache.org/v1alpha1"
kind: "Druid"
metadata:
  name: tiny-cluster
spec:
  podLabels:
    label_a: yes
  nodes:
    brokers:
      podLabels:
        label_b: yes
```
