### ISSUE TITLE
[AWS] Coordinator keeps crashing

### ISSUE THREAD

**Issue by EliottTardieu** [datainfrahq/druid-operator#195]
Hi, I'm writing to you as a last resort, can't seem to find out what I'm doing wrong...
I'm running Druid using your simple cluster + operator, and my coordinator keeps crashing with no log whatsoever.
Here are the yaml files:

values.yaml
```
# Default values for druid-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

env:
  DENY_LIST: "default,kube-system" # Comma-separated list of namespaces to ignore
  RECONCILE_WAIT: "10s" # Reconciliation delay
  WATCH_NAMESPACE: "" # Namespace to watch or empty string to watch all namespaces, To watch multiple namespaces add , into string. Ex: WATCH_NAMESPACE: "ns1,ns2,ns3"
  #MAX_CONCURRENT_RECONCILES:: ""  # MaxConcurrentReconciles is the maximum number of concurrent Reconciles which can be run.

replicaCount: 1

image:
  repository: datainfrahq/druid-operator
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

kube_rbac_proxy:
  image:
    repository: gcr.io/kubebuilder/kube-rbac-proxy
    pullPolicy: IfNotPresent
    tag: "v0.13.1"


imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

livenessProbe:
  httpGet:
    path: /healthz
    port: 8081
  initialDelaySeconds: 15
  periodSeconds: 20

readinessProbe:
  httpGet:
    path: /readyz
    port: 8081
  initialDelaySeconds: 5
  periodSeconds: 10

serviceAccount:
  # Annotations to add to the service account
  annotations:
    kubectl.kubernetes.io/default-container: manager
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: "druid-operator-controller-manager"

podAnnotations: {}

podSecurityContext:
  runAsNonRoot: true
  fsGroup: 65532
  runAsUser: 65532
  runAsGroup: 65532

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL

resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 64Mi

nodeSelector: {}

tolerations: []

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/arch
              operator: In
              values:
                - amd64
                - arm64
                - ppc64le
                - s390x
            - key: kubernetes.io/os
              operator: In
              values:
                - linux

crd:
  enabled: true
  keep: true
```

cluster:
```
apiVersion: "druid.apache.org/v1alpha1"
kind: "Druid"
metadata:
  name: druid-cluster
spec:
  image: apache/druid:31.0.0
  # Optionally specify image for all nodes. Can be specify on nodes also
  # imagePullSecrets:
  # - name: tutu
  priorityClassName: high-priority
  startScript: /druid.sh
  podLabels:
    environment: stage
    release: alpha
  podAnnotations:
    dummykey: dummyval
  readinessProbe:
    httpGet:
      path: /status/health
      port: 8088
  securityContext:
    fsGroup: 1000
    runAsUser: 0
    runAsGroup: 0
  services:
    - spec:
        type: ClusterIP
        clusterIP: None
  commonConfigMountPath: "/opt/druid/conf/druid/cluster/_common"
  jvm.options: |-
    -server
    -XX:MaxDirectMemorySize=10240g
    -Duser.timezone=UTC
    -Dfile.encoding=UTF-8
    -Dlog4j.debug
    -Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager
    -Djava.io.tmpdir=/druid/data
  log4j.config: |-
    <?xml version="1.0" encoding="UTF-8" ?>
    <Configuration status="WARN">
        <Appenders>
            <Console name="Console" target="SYSTEM_OUT">
                <PatternLayout pattern="%d{ISO8601} %p [%t] %c - %m%n"/>
            </Console>
        </Appenders>
        <Loggers>
            <Root level="info">
                <AppenderRef ref="Console"/>
            </Root>
        </Loggers>
    </Configuration>
  common.runtime.properties: |

    # Zookeeper
    druid.zk.service.host=zookeeper.smartx.svc.cluster.local
    druid.zk.paths.base=/druid
    druid.zk.service.compress=false

    druid.metadata.storage.type=postgresql
    druid.metadata.storage.connector.connectURI=jdbc:postgresql://postgres.smartx.svc.cluster.local:5432/druid
    druid.metadata.storage.connector.user=postgres
    druid.metadata.storage.connector.password=postgres

    # Deep Storage
    druid.storage.type=local
    druid.storage.storageDirectory=/druid/storage

    #
    # Extensions
    #
    druid.extensions.loadList=["druid-kafka-indexing-service","postgresql-metadata-storage","druid-multi-stage-query"]


    #
    # Service discovery
    #
    druid.selectors.indexing.serviceName=druid/overlord
    druid.selectors.coordinator.serviceName=druid/coordinator

    druid.indexer.logs.type=file
    druid.indexer.logs.directory=/druid/data/logs

    druid.segmentCache.locations=[{"path":"/druid/data/segment-cache","maxSize":10737418240}]
    druid.indexer.logs.directory=/druid/data/indexing-logs
    druid.lookup.enableLookupSyncOnStartup=false
    druid.worker.capacity=3
  volumeMounts:
    - mountPath: /druid/data
      name: data-volume
    - mountPath: /druid/storage
      name: storage-volume
    - mountPath: /druid/filestorage
      name: storage-file-volume
  volumes:
    - name: data-volume
      emptyDir: {}
    - name: storage-volume
      persistentVolumeClaim:
        claimName: druid-storage
    - name: storage-file-volume
      persistentVolumeClaim:
        claimName: druid-file-storage
  env:
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace

  nodes:
    brokers:
      # Optionally specify for running broker as Deployment
      # kind: Deployment
      nodeType: "broker"
      # Optionally specify for broker nodes
      # imagePullSecrets:
      # - name: tutu
      druid.port: 8088
      nodeConfigMountPath: "/opt/druid/conf/druid/cluster/query/broker"
      replicas: 1
      resources:
        requests:
          cpu: "0.5"
          memory: 6Gi
        limits:
          memory: 6Gi
      runtime.properties: |
        druid.service=druid/broker
        # HTTP server threads
        druid.broker.http.numConnections=50
        druid.server.http.numThreads=60
        # Processing threads and buffers
        druid.processing.buffer.sizeBytes=500MiB
        druid.processing.numMergeBuffers=4
        druid.processing.numThreads=1
        druid.sql.enable=true
        druid.server.http.defaultQueryTimeout=3000000
      extra.jvm.options: |-
        -Xmx4G
        -Xms4G

    coordinators: #FIXME Crash every 5 minutes....
      # Optionally specify for running coordinator as Deployment
      # kind: Deployment
      nodeType: "coordinator"
      druid.port: 8088
      nodeConfigMountPath: "/opt/druid/conf/druid/cluster/master/coordinator-overlord"
      replicas: 3
      resources:
        requests:
          cpu: "0.5"
          memory: 4Gi
        limits:
          memory: 4Gi
      runtime.properties: |
        druid.service=druid/coordinator

        # HTTP server threads
        druid.coordinator.startDelay=PT30S
        druid.coordinator.period=PT30S

        # Configure this coordinator to also run as Overlord
        druid.coordinator.asOverlord.enabled=true
        druid.coordinator.asOverlord.overlordService=druid/overlord
        druid.indexer.queue.startDelay=PT30S
        druid.indexer.runner.type=local
      extra.jvm.options: |-
        -Xmx4G
        -Xms4G

    historicals:
      nodeType: "historical"
      druid.port: 8088
      nodeConfigMountPath: "/opt/druid/conf/druid/cluster/data/historical"
      replicas: 2
      resources:
        requests:
          cpu: "0.5"
          memory: 4Gi
        limits:
          memory: 4Gi
      runtime.properties: |
        druid.service=druid/historical
        druid.server.http.numThreads=5
        druid.processing.buffer.sizeBytes=536870912
        druid.processing.numMergeBuffers=1
        druid.processing.numThreads=1
        druid.historical.cache.useCache=true
        druid.historical.cache.populateCache=true
        druid.server.http.defaultQueryTimeout=3000000

        # Segment storage
        druid.segmentCache.locations=[{\"path\":\"/druid/data/segment-cache\",\"maxSize\":100737418240}]
        druid.server.maxSize=100737418240
      extra.jvm.options: |-
        -Xmx4G
        -Xms4G

    routers:
      nodeType: "router"
      druid.port: 8088
      nodeConfigMountPath: "/opt/druid/conf/druid/cluster/query/router"
      replicas: 1
      resources:
        requests:
          cpu: "0.5"
          memory: 4Gi
        limits:
          memory: 4Gi
      runtime.properties: |
        druid.service=druid/router

        # HTTP proxy
        druid.router.http.numConnections=10
        druid.router.http.readTimeout=PT5M
        druid.router.http.numMaxThreads=10
        druid.server.http.numThreads=10

        # Service discovery
        druid.router.defaultBrokerServiceName=druid/broker
        druid.router.coordinatorServiceName=druid/coordinator

        # Management proxy to coordinator / overlord: required for unified web console.
        druid.router.managementProxy.enabled=true
      extra.jvm.options: |-
        -Xmx2G
        -Xms2G
```

zk:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper-deployment
  template:
    metadata:
      labels:
        app: zookeeper-deployment
    spec:
      containers:
        - name: zookeeper
          image: zookeeper:3.8.4
          ports:
            - containerPort: 2181
          env:
            - name: ZOOKEEPER_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          volumeMounts:
            - mountPath: /data
              name: zk-volume
      volumes:
        - name: zk-volume
          persistentVolumeClaim:
            claimName: pvc-zookeeper
```

## Issue description
Basically, the coordinators crashes every 5 minutes (sometimes less, sometimes more), without any logs. Can't see any logs in zookeeper, nor pg metadata db. Can't see any logs in druid, nor syslog. Doesn't seem to get OOM, so I'm kinda clueless about what's going on here. Not sure if it's the best place to ask but any help / redirection to proper place would be greatly appreciated. 

### Specs
I'm running on EC2 instances (4*t3.xlarge) using EFS (Elastic File System) as deep storage. 
About 80k segments (maybe it's a scale issue, can't seem to figure it out).
BONUS: I tried setting up compaction, it stayed in 'Awaiting first run' forever.

## What I already tried
- Changing JVM / K8S config to ensure it wasn't OOM.
- Upscaling / Downscaling coordinator, ensuring it wasn't a replica issue.
- Checking syslog (no logs).

Thank you.
