### ISSUE TITLE
Add Compaction taskslots spec to coordinator config

### ISSUE THREAD

**Issue by SatyaKuppam** [datainfrahq/druid-operator#210]
We can set the number of tasks a cluster can use for auto-compaction using `config/compaction/taskslots` ([ref](https://druid.apache.org/docs/latest/api-reference/automatic-compaction-api#url-2)). This is a cluster level setting. #197 introduced adding dynamic configuration to the coordinator. This configuration is not part of the coordinator dynamic config and hence we need to make a second call to update this config. I can work on adding this, but I am not sure whats the best way to do this, I like the following

### in the coordinator spec separately

```
nodeSpec:
   coordinator:
      dynamicConfig: ...
      autoCompactionConfig:
       compactionTaskSlotRatio: ...
       maxCompactionTaskSlots:  ...
```
because:
* a `GET` call to `coordinator/v1/config/compaction` will return both `compactionTaskSlotRatio` and `maxCompactionTaskSlots`
* its also cleaner because logically its not part of the coordinator dynamic configuration
