### ISSUE TITLE
[Proposal] Ingestion Spec controller

### ISSUE THREAD

**Issue by AdheipSingh** [datainfrahq/druid-operator#3]
- In ref: Proposal: Ingestion Spec controller  druid-io/druid-operator#313

**Comment by AdheipSingh** [comment]
@styk-tv I will be sending a draft PR. Your reviews and testing would be really helpful. 
Thank you for collaboration.

**Comment by itamar-marom** [comment]
Regarding the field: `supervisorSpec` </br>
Instead of spiling an entire JSON, a more common way is to do a reference to a configmap. or secret For example: </br>
```yaml
apiVersion: "druid.apache.org/v1alpha1"
kind: "DruidIngestion"
metadata:
  name: sample-druid-spec
  namespace: mydruid
spec:
  clusterRef: mydruid
  suspend: false
  supervisorSpecRef:
     kind: ConfigMap
     name: mysupervisor
     namespace: druid
```

and hold an object like this:
```go
type CrossNamespaceSourceReference struct {
	// API version of the referent.
	// +optional
	APIVersion string `json:"apiVersion,omitempty"`

	// Kind of the referent.
	// +required
	Kind string `json:"kind"`

	// Name of the referent.
	// +required
	Name string `json:"name"`

	// Namespace of the referent, defaults to the namespace of the Kubernetes resource object that contains the reference.
	// +optional
	Namespace string `json:"namespace,omitempty"`
}
```
