### ISSUE TITLE
[proposal] Setup default probe for each nodes types 

### ISSUE THREAD

**Issue by cyril-corbon** [datainfrahq/druid-operator#55]
## Context & goal

All the druid components deployed by the operator are deployed by default without probe.
IMHO an operator have to configure in advance this kind of settings.  

Probes have to be configured for each node type and override if an user has defined it.  

all the different probes have to use the [druid api reference](https://druid.apache.org/docs/latest/operations/api-reference.html)

### coordinator, overlord, middlemanager and router

```yaml
      livenessProbe:
        httpGet:
          path: /status/health
          port: $druid.port
        failureThreshold: 20
        initialDelaySeconds: 5
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 5
      readinessProbe:
        httpGet:
          path: /status/health
          port: $druid.port
        failureThreshold: 10
        initialDelaySeconds: 5
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 5
```

### broker

```yaml
      livenessProbe:
        httpGet:
          path: /status/health
          port: $druid.port
        failureThreshold: 20
        initialDelaySeconds: 5
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 5
      readinessProbe:
        httpGet:
          path: /druid/broker/v1/readiness
          port: $druid.port
        failureThreshold: 10
        initialDelaySeconds: 5
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 5
```

### historical

```yaml
      livenessProbe:
        httpGet:
          path: /status/health
          port: $druid.port
        failureThreshold: 20
        initialDelaySeconds: 5
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 5
      readinessProbe:
        httpGet:
          path: /status/health
          port: $druid.port
        failureThreshold: 10
        initialDelaySeconds: 5
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 5
      startUpProbes:
        httpGet:
          path: /druid/historical/v1/loadstatus
          port: $druid.port
        failureThreshold: 20
        initialDelaySeconds: 180
        periodSeconds: 30
        successThreshold: 1
        timeoutSeconds: 10
      
```
